# Generated by Django 3.2.3 on 2021-05-19 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotifyList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pincode', models.IntegerField(max_length=6)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Phone_no', models.IntegerField(max_length=10)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
