# Generated by Django 3.2.3 on 2021-05-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vax_notify', '0003_alter_notifylist_phone_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notified_members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_no', models.CharField(blank=True, max_length=10, null=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
